services:
  - type: worker
    name: bitcoin-forecast-bot
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: BITGET_APIKEY
        fromDatabase: true
      - key: BITGET_APISECRET
        fromDatabase: true
      - key: BITGET_PASSPHRASE
        fromDatabase: true
      - key: OPENAI_API_KEY
        fromDatabase: true
      - key: TELEGRAM_BOT_TOKEN
        fromDatabase: true
      - key: TELEGRAM_CHAT_ID
        fromDatabase: true
      - key: PUBLICITY_API_KEY
        fromDatabase: true
